### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by franciscoperalta** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#10]
Hello, first of all, thank you for sharing the code. After I clone, prepare the datasets and download the checkpoint, I tried tu run it but I get this error everytime `ValueError: num_samples should be a positive integer value, but got num_samples=0`. The error seems to be in the line 55 of the file model\runner.py `l = DataLoader(d, **loader_opts)`. I hope you can help me. Thank you :)

**Comment by heqin-zhu** [comment]
Thanks for your feedback. It seems that the datasets weren't loaded properly.  You can check the following items:
1. Make sure all datasets and labels are completely downloaded
2. Make sure the directory structure is properly organized
3. Add a line `assert len(d)>0, 'load {} {} set failed'.format(name,s)'` before line 55 and rerun the script, you will get more specific error messege.

**Comment by franciscoperalta** [comment]
Thanks for your answer, after I make sure all datasets and labels are completely downloaded and the directory structure is properly organized, I added the line and I get `load cephalometric test set failed`

**Comment by heqin-zhu** [comment]
As the message indicates, the test set of cephalometric(head) dataset is not downloaded. Make sure that directory `data/ISBI2015_ceph/raw` contains 400 images.
