### ISSUE TITLE
how to visualize the results？

### ISSUE THREAD

**Issue by benzzhang** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#12]
After testing，I got results included some .png and .npy 
I want to know how to fuse them to show the points in the Chest X-Ray pics.
I used the following code，it didn't work：
```
import numpy as np
import cv2
import matplotlib.pyplot as plt
image = np.load(r'D:\code-zhangjian\code-space\src\chest\CHNCXR_0032_0_gt.npy')
src = plt.imread(r'D:\code-zhangjian\code-space\src\CHNCXR_0032_0.png')
for i in range(0,image.shape[0]):
    plt.imshow(image[i,:,:],cmap='gray')
    plt.imshow(src,cmap='gray')
    cv2.imwrite(str(i)+".png",image[i,:,:])
    plt.show()
```

**Comment by heqin-zhu** [comment]
The visualization code is in `evaluation.py`. You can add `-ds` arguments at the evaluation stage to generate visualization results.  For example, `python3 evaluation.py -i ../runs/GU2Net/results/test_epoch067 -ds`.

**Comment by benzzhang** [comment]
the arguments should be ‘-s’

发自我的iPhone

> 在 2022年5月2日，下午2:06，Heqin Zhu ***@***.***> 写道：
> 
> arguments
