### ISSUE TITLE
手部数据有问题

### ISSUE THREAD

**Issue by 1419786491** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#14]
您好,我在下载手部数据后,发现和all.csv里的文件很大一部分对不上,下载的共有1028个jpg文件,但csv上有对应标注的只有600个,其他都不能找到标注,你有处理过的数据吗 谢谢

**Comment by heqin-zhu** [comment]
是的，手部数据的标注只有一部分，代码中已经处理好这一点，即筛选出有标注数据的图像文件，如下
https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection/blob/23ec0b921e6c15d040f36650fd862059745edc33/universal_landmark_detection/model/datasets/hand.py#L28

**Comment by 1419786491** [comment]
感谢回复,但是我这样处理后一共只有681张图像,并没有909个用于train和 test   是我下载出问题了还是这个数据集做了一些改动呢

**Comment by 1419786491** [comment]
解决了  感谢老哥,下载出了问题  部分数据没有下载完
