### ISSUE TITLE
The `chest_label.zip` is empty and can you provide me the dataset 

### ISSUE THREAD

**Issue by swetharethinavel** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#17]
The `chest_label.zip` is not empty and it's link is [YOLO_Universal_Anatomical_Landmark_Detection/data/chest_labels.zip](https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection/tree/main/data/chest_labels.zip). The GitHub webpage won't display it since it's a zip file. You can `git clone` or `download` this repo and fetch it through above path.

_Originally posted by @heqin-zhu in https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection/issues/16#issuecomment-1345918805_

**Comment by swetharethinavel** [comment]
i have cloned it and also i have downloaded it ,even after extracting them all ,it is showing that the file is empty .

and can you please provide me the dataset for this model

**Comment by heqin-zhu** [comment]
The `chest_labels.zip` have been updated and you can check it. I am sorry that I have no right and no way to distribute these datasets.
