### ISSUE TITLE
Shared head Dataset link cannot download anymore

### ISSUE THREAD

**Issue by zhongxinyun** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#19]
The shared head dataset link1 in figshare website cannot download anymore, can you update the link again?

**Comment by heqin-zhu** [comment]
I don't maintain the head dataset. You may try to fetch this dataset via [link2](https://www.kaggle.com/datasets/c34a0ef0cd3cfd5c5afbdb30f8541e887171f19f196b1ad63790ca5b28c0ec93) alternatively.
