### ISSUE TITLE
Performing Inference on an Image not included in the Dataset using the Pre-trained Model (best.pt)

### ISSUE THREAD

**Issue by yann86** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#20]
Hello,

I am trying to use the pre-trained model (best.pt) provided by you. I would like to use the pre-trained model to make predictions on new images that were not part of the dataset used during training. 

In addition to understanding how to use the pre-trained model for inference on unseen images, I would like to know if there are any specific size requirements or considerations for the input image. Should I resize or preprocess my images to a particular size before feeding them into the model for inference? If so, what are the recommended dimensions or any other relevant guidelines?

I would greatly appreciate your guidance, documentation, code snippets, or instructions regarding the necessary steps and considerations for utilizing the pre-trained model (best.pt) on images that were not included in the dataset.

Thank you very much for your assistance!

**Comment by heqin-zhu** [comment]
Sorry to reply you so late.

The size of input image is defined in `config.yaml` and corresponding dataset file (i.e., `universal_landmark_detection/model/datasets`). You can regard the new image as an "hand" image and change related parameters (e.g. size, path...) of hand dataset in `config.yaml`. Another method is to create a new dataset file (similar to hand.py)  for the new image and add new parameters in `config.yaml`.

 It's hard to inference new images by using the pre-trained model. The results may be unsatisfying when the new image has a huge domain gap between the pre-trained datasets.

You'd better read and understand the codes before you use the pre-trained model on  images from a new domain.
