### ISSUE TITLE
Weakmethod object error using torch.save

### ISSUE THREAD

**Issue by jankooovic** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#21]
Hello, 
I have encountered an error with pztorch.save - cannot pickle weakmethod object error and opened a quesion on StackOverflow. 
https://stackoverflow.com/questions/76738857/why-do-i-get-a-weakmethod-object-error-when-using-torch-save

Is there maybe a solution for this error?

Best regards,
Jan

**Comment by heqin-zhu** [comment]
Hello, 

Thanks for your question. There is a bug of the code. It can be quickly solved by commenting [line 270](https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection/blob/622987667b3ed3bb3bb225fff32296329e402739/universal_landmark_detection/model/runner.py#L270) in `runner.py`.
