### ISSUE TITLE
The file of "all.csv" of hand can't downloads from the original website. 

### ISSUE THREAD

**Issue by switch626** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#9]
Hello Heqin, great work!
I want to download the data of the landmarks annotation of the hand, but the original submission download information has been invalid, so can you share the all.csv file? Thanks!

**Comment by switch626** [comment]
This is my email address: xw2009@hw.ac.uk

**Comment by heqin-zhu** [comment]
Thanks for your feedback. You can find `all.csv` in [Payer's repo](https://github.com/christianpayer/MedicalDataAugmentationTool-HeatmapRegression/blob/master/hand_xray/hand_xray_dataset/setup/all.csv).
